### ISSUE TITLE
Provide ability to push envvars without triggering

### ISSUE THREAD

**Issue by jritsema** [turnerlabs/harbor-compose#121]
Currently, the up command pushes up environment variables from compose files and triggers.  The [ignoreImageVersion](https://github.com/turnerlabs/harbor-compose/blob/master/compose-reference.md#ignoreimageversion) property in harbor-compose.yml allows you to not deploy an image, however, changes are still triggered so that environment variables and replica changes take effect immediately against the current image.

It might be nice to have a command for scenarios where you don't want the environment variable changes to trigger a deployment immediately, and instead, you want them to be "queued up" pending the next CI/CD deployment.

What would folks think about the following?
```
$ harbor-compose envvars push
$ harbor-compose envvars pull
```

**Comment by kendavis2** [comment]
That would be very useful. Would it only push new env vars? It would be fantastic if it could remove any that have been removed locally.

**Comment by jritsema** [comment]
@kendavis2 currently only updates envvars defined in compose files.  We were holding off on deletes until we fully support ["hidden" envvars](https://github.com/turnerlabs/harbor-compose/issues/19) since folks may be creating those outside and we don't want to delete them.

**Comment by TrippBlunschi** [comment]
I think this would be a great feature. Currently, there's no way to update variables (without using the UI) and not have a re-deploy occur against the currently deployed image. While this does create an "out of sync" situation between what variables are currently deployed and what variables are displayed in the UI, this can be easily solved by having (non-hidden) variables stored in source control if it's necessary to view or roll back the environment variables to what is currently deployed. 

I would also be in support of this operation being allowed to execute in a CI/CD like CircleCI so that these variables could be pushed as part of a commit, with the understanding that hidden variables shouldn't be stored in source control and not be part of the push. Hidden variables should be entered into the UI until a more secure solution is implemented.
